Checking yaml  CICD

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -235,85 +235,16 @@
 
 
 #################################################################
-#name: Continuous Integration
-#
-#on:
-##  workflow_call:
-#  push:
-#    branches:
-#      - jagannath
-#
-#concurrency:
-#  group: jagannath
-#  cancel-in-progress: true
-#
-#jobs:
-#  deploy:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - name: Configure SSH
-#        env:
-#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-#          SSH_HOST: ${{ secrets.SSH_HOST }}
-#          SSH_USER: ${{ secrets.SSH_USER }}
-#        run: |
-#          mkdir -p ~/.ssh/
-#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
-#          chmod 600 ~/.ssh/github
-#          cat >> ~/.ssh/config <<END
-#          Host target
-#            HostName $SSH_HOST
-#            User $SSH_USER
-#            IdentityFile ~/.ssh/github
-#            LogLevel ERROR
-#            StrictHostKeyChecking no
-#          END
-#      - name: Checking Screen
-#        run: |
-#          ssh target "sudo screen -list"
-#      - name: Run deploy
-#        run: |
-#          ssh target << 'EOF'
-#          sudo pkill -f 'python manage.py runserver 0.0.0.0:2914'
-#          echo "service stopped"
-#          sleep 5  # Wait for the server to stop
-#          #################################################################
-#            # Check if the screen session exists
-#            if sudo screen -list | grep -q 150841; then
-#              echo "Screen session found. Proceeding with deployment."
-#              ##################################################################
-#              # Force pull the latest changes
-#              sudo screen -S 150841 -X stuff 'cd /home/ubuntu/cicd_project/cicd\n'
-#              #cd /home/ubuntu/cicd_project/cicd\n
-#              sudo screen -S 150841 -X stuff 'git pull\n'
-#              #git fetch origin
-#              #git reset --hard origin/jagannath
-#              ##################################################################
-#              # Start the server again in the screen session
-#              sudo screen -S 150841 -X stuff 'source /home/ubuntu/cicd_project/cicd_env/bin/activate\n'
-#              echo "env activated."
-#              sudo screen -S 150841 -X stuff 'pip install -r requirements.txt\n'
-#              echo "Installing requirements"
-#              sleep 5
-#              sudo screen -S 150841 -X stuff 'python manage.py runserver 0.0.0.0:2914\n'
-#              echo "deployed."
-#            else
-#              echo "No screen session found. Aborting. Hi jagannath"
-#              exit 1
-#            fi
-#          EOF
-#############################################################################
 name: Continuous Integration
 
 on:
-  workflow_call:
   push:
     branches:
       - jagannath
 
-#concurrency:
-#  group: jagannath
-#  cancel-in-progress: true
+concurrency:
+  group: jagannath
+  cancel-in-progress: true
 
 jobs:
   deploy:
@@ -321,9 +252,9 @@ jobs:
     steps:
       - name: Configure SSH
         env:
-          SSH_PRIVATE_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
-          SSH_HOST: ${{ inputs.SSH_HOST }}
-          SSH_USER: ${{ inputs.SSH_USER }}
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SSH_HOST: ${{ secrets.SSH_HOST }}
+          SSH_USER: ${{ secrets.SSH_USER }}
         run: |
           mkdir -p ~/.ssh/
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
@@ -370,3 +301,78 @@ jobs:
               exit 1
             fi
           EOF
+      - name: Checking server Status
+        run: |
+          ps aux | grep 'python manage.py runserver 0.0.0.0:2914' | grep -v grep
+        id: check_server_status
+
+      - name: Print server status
+        run: echo "${{ steps.check_server_status.outputs }}"
+#############################################################################
+#name: Continuous Integration
+#
+#on:
+#  workflow_call:
+#  push:
+#    branches:
+#      - jagannath
+#
+##concurrency:
+##  group: jagannath
+##  cancel-in-progress: true
+#
+#jobs:
+#  deploy:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Configure SSH
+#        env:
+#          SSH_PRIVATE_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
+#          SSH_HOST: ${{ inputs.SSH_HOST }}
+#          SSH_USER: ${{ inputs.SSH_USER }}
+#        run: |
+#          mkdir -p ~/.ssh/
+#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github
+#          chmod 600 ~/.ssh/github
+#          cat >> ~/.ssh/config <<END
+#          Host target
+#            HostName $SSH_HOST
+#            User $SSH_USER
+#            IdentityFile ~/.ssh/github
+#            LogLevel ERROR
+#            StrictHostKeyChecking no
+#          END
+#      - name: Checking Screen
+#        run: |
+#          ssh target "sudo screen -list"
+#      - name: Run deploy
+#        run: |
+#          ssh target << 'EOF'
+#          sudo pkill -f 'python manage.py runserver 0.0.0.0:2914'
+#          echo "service stopped"
+#          sleep 5  # Wait for the server to stop
+#          #################################################################
+#            # Check if the screen session exists
+#            if sudo screen -list | grep -q 150841; then
+#              echo "Screen session found. Proceeding with deployment."
+#              ##################################################################
+#              # Force pull the latest changes
+#              sudo screen -S 150841 -X stuff 'cd /home/ubuntu/cicd_project/cicd\n'
+#              #cd /home/ubuntu/cicd_project/cicd\n
+#              sudo screen -S 150841 -X stuff 'git pull\n'
+#              #git fetch origin
+#              #git reset --hard origin/jagannath
+#              ##################################################################
+#              # Start the server again in the screen session
+#              sudo screen -S 150841 -X stuff 'source /home/ubuntu/cicd_project/cicd_env/bin/activate\n'
+#              echo "env activated."
+#              sudo screen -S 150841 -X stuff 'pip install -r requirements.txt\n'
+#              echo "Installing requirements"
+#              sleep 5
+#              sudo screen -S 150841 -X stuff 'python manage.py runserver 0.0.0.0:2914\n'
+#              echo "deployed."
+#            else
+#              echo "No screen session found. Aborting. Hi jagannath"
+#              exit 1
+#            fi
+#          EOF
